// File generated by FlutterFire CLI.
// This is a placeholder - run `flutterfire configure` to generate actual values
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIaYayfbk9xuyFI3KJB1PlYtngZeh9VnU',
    appId: '1:994893675209:web:12d18aa4a6de4d8b642b18',
    messagingSenderId: '994893675209',
    projectId: 'kolorkash-3d',
    authDomain: 'kolorkash-3d.firebaseapp.com',
    storageBucket: 'kolorkash-3d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXCEi0earSqO5hYHsSNQnYirEdtDObE1A',
    appId: '1:994893675209:android:ed24056b57534e76642b18',
    messagingSenderId: '994893675209',
    projectId: 'kolorkash-3d',
    storageBucket: 'kolorkash-3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDclqMb4woL7civpLCy_LPdr214xuGD8Vc',
    appId: '1:994893675209:ios:87203d0b43100247642b18',
    messagingSenderId: '994893675209',
    projectId: 'kolorkash-3d',
    storageBucket: 'kolorkash-3d.firebasestorage.app',
    iosBundleId: 'com.example.kolorKash3d',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDclqMb4woL7civpLCy_LPdr214xuGD8Vc',
    appId: '1:994893675209:ios:87203d0b43100247642b18',
    messagingSenderId: '994893675209',
    projectId: 'kolorkash-3d',
    storageBucket: 'kolorkash-3d.firebasestorage.app',
    iosBundleId: 'com.example.kolorKash3d',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIaYayfbk9xuyFI3KJB1PlYtngZeh9VnU',
    appId: '1:994893675209:web:12d18aa4a6de4d8b642b18',
    messagingSenderId: '994893675209',
    projectId: 'kolorkash-3d',
    authDomain: 'kolorkash-3d.firebaseapp.com',
    storageBucket: 'kolorkash-3d.firebasestorage.app',
  );

}